In [15]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\cpall\appdata\local\programs\python\python312\lib\site-packages (2.0.44)
Requirement already satisfied: greenlet>=1 in c:\users\cpall\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\cpall\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\cpall\appdata\local\programs\python\python312\lib\site-packages (1.1.2)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
import pandas as pd
import numpy as np
import pymysql
from sqlalchemy import create_engine
import getpass  # To get the password without showing the input
password = getpass.getpass()

In [18]:
# Establish a connection between Python and the Sakila database.
import getpass
from sqlalchemy import create_engine, text  # <- import text

password = getpass.getpass("Enter MySQL root password: ")

bd = "Sakila"
connection_string = f"mysql+pymysql://root:{password}@localhost/{bd}"

engine = create_engine(connection_string)

# Test connection
with engine.connect() as connection:
    result = connection.execute(text("SELECT DATABASE();"))  # <- wrap SQL in text()
    print(result.fetchone())

('sakila',)

In [27]:
# 2. Write a Python function called `rentals_month` that retrieves rental data for a given month and year (passed as parameters) from the Sakila database as a Pandas DataFrame. The function should take in three parameters:
#	- `engine`: an object representing the database connection engine to be used to establish a connection to the Sakila database.
#	- `month`: an integer representing the month for which rental data is to be retrieved.
#	- `year`: an integer representing the year for which rental data is to be retrieved.
#	The function should execute a SQL query to retrieve the rental data for the specified month and year from the rental table in the Sakila database,
#  and return it as a pandas DataFrame.
     
def rental_month(engine, month, year):
    """
    Retrieves rental data for a given month and year from the Sakila database.

    Parameters:
    engine : SQLAlchemy engine
        Database connection engine to the Sakila database.
    month : int
        Month (1-12) for which to retrieve rental data.
    year : int
        Year (e.g., 2023) for which to retrieve rental data.

    Returns:
    pd.DataFrame
        DataFrame containing rental data for the specified month and year.
    """
        # SQL query to get rentals for the given month and year # Use text() to safely pass SQL with parameters
    query = text("""   
        SELECT *
        FROM rental
        WHERE MONTH(rental_date) = :month
          AND YEAR(rental_date) = :year
    """)
        # Execute query and return result as DataFrame
    with engine.connect() as connection:
        df = pd.read_sql(query, connection, params={"month": month, "year": year})  # :month and :year are placeholders to avoid SQL injection
    
    return df

In [28]:
# 3. Develop a Python function called `rental_count_month` that takes the DataFrame provided by `rentals_month` as input
#   along with the month and year and returns a new DataFrame containing the number of rentals made by each customer_id
#   during the selected month and year. 
#	The function should also include the month and year as parameters and use them to name the new column according to the month and year,
#  for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".
#	*Hint: Consider making use of pandas [groupby()]

import pandas as pd

def rental_count_month(df, month, year):
    """
    Takes the DataFrame from rentals_month and returns a new DataFrame 
    containing the number of rentals made by each customer_id during the selected month and year.
    
    Parameters:
    df : pd.DataFrame
        DataFrame from rentals_month function.
    month : int
        Month for which rental counts are calculated.
    year : int
        Year for which rental counts are calculated.
    
    Returns:
    pd.DataFrame
        DataFrame with 'customer_id' and rental count column named according to month and year.
    """
    # Group by customer_id and count rentals
    rental_counts = df.groupby('customer_id').size().reset_index(name=f"rentals_{month:02d}_{year}")
    
    return rental_counts

In [29]:
# 4. Create a Python function called compare_rentals that takes two DataFrames as input
# containing the number of rentals made by each customer in different months and years.
# The function should return a combined DataFrame with a new 'difference' column, 
# which is the difference between the number of rentals in the two months.
import pandas as pd

def compare_rentals(df1, df2):
    """
    Compare rental counts between two DataFrames for different months/years.

    Parameters:
    df1 : pd.DataFrame
        DataFrame containing 'customer_id' and rental counts for the first month/year.
    df2 : pd.DataFrame
        DataFrame containing 'customer_id' and rental counts for the second month/year.

    Returns:
    pd.DataFrame
        Combined DataFrame with rental counts from both months and a 'difference' column
        (df2 count - df1 count).
    """
    # Merge the two DataFrames on customer_id (outer join to include all customers)
     # Fill NaN values with 0 (customers who didn't rent in one of the months)
    combined_df = pd.merge(df1, df2, on='customer_id', how='outer').fillna(0)

    # Identify the rental count columns (assumes only one column besides customer_id)
    col1 = [c for c in df1.columns if c != 'customer_id'][0]
    col2 = [c for c in df2.columns if c != 'customer_id'][0]

    # Create the difference column
    combined_df['difference'] = combined_df[col2] - combined_df[col1]

    return combined_df

In [31]:
# Analysis: Get rental data for May 2005
may_rentals = rental_month(engine, 5, 2005)
print(f"Total rentals in May 2005: {len(may_rentals)}")
print("\nFirst 5 rows of May rental data:")
display(may_rentals.head())

Total rentals in May 2005: 1156

First 5 rows of May rental data:

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

In [32]:
# Analysis: Get rental data for June 2005
june_rentals = rental_month(engine, 6, 2005)
print(f"Total rentals in June 2005: {len(june_rentals)}")
print("\nFirst 5 rows of June rental data:")
display(june_rentals.head())

Total rentals in June 2005: 2311

First 5 rows of June rental data:

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1158,2005-06-14 22:53:33,1632,416,2005-06-18 21:37:33,2,2006-02-15 21:30:53
1,1159,2005-06-14 22:55:13,4395,516,2005-06-17 02:11:13,1,2006-02-15 21:30:53
2,1160,2005-06-14 23:00:34,2795,239,2005-06-18 01:58:34,2,2006-02-15 21:30:53
3,1161,2005-06-14 23:07:08,1690,285,2005-06-21 17:12:08,1,2006-02-15 21:30:53
4,1162,2005-06-14 23:09:38,987,310,2005-06-23 22:00:38,1,2006-02-15 21:30:53

In [33]:
# Get rental counts per customer for each month
may_counts = rental_count_month(may_rentals, 5, 2005)
june_counts = rental_count_month(june_rentals, 6, 2005)

print(f"Number of customers who rented in May 2005: {len(may_counts)}")
print(f"Number of customers who rented in June 2005: {len(june_counts)}")

print("\nTop 5 customers in May:")
display(may_counts.nlargest(5, 'rentals_05_2005'))

print("\nTop 5 customers in June:")
display(june_counts.nlargest(5, 'rentals_06_2005'))

Number of customers who rented in May 2005: 520
Number of customers who rented in June 2005: 590

Top 5 customers in May:

     customer_id  rentals_05_2005
168          197                8
92           109                7
441          506                7
15            19                6
43            53                6

Top 5 customers in June:

     customer_id  rentals_06_2005
30            31               11
445          454               10
209          213                9
263          267                9
291          295                9

In [34]:
# Compare the two months
comparison = compare_rentals(may_counts, june_counts)
print(f"Total customers active in either month: {len(comparison)}")

# Show customers who were active in both months
active_both_months = comparison[(comparison['rentals_05_2005'] > 0) & (comparison['rentals_06_2005'] > 0)]
print(f"Customers active in BOTH May and June: {len(active_both_months)}")

print("\nComparison DataFrame (first 10 rows):")
display(comparison.head(10))

Total customers active in either month: 598
Customers active in BOTH May and June: 512

Comparison DataFrame (first 10 rows):

   customer_id  rentals_05_2005  rentals_06_2005  difference
0            1              2.0              7.0         5.0
1            2              1.0              1.0         0.0
2            3              2.0              4.0         2.0
3            4              0.0              6.0         6.0
4            5              3.0              5.0         2.0
5            6              3.0              4.0         1.0
6            7              5.0              5.0         0.0
7            8              1.0              3.0         2.0
8            9              3.0              2.0        -1.0
9           10              1.0              5.0         4.0

In [35]:

# Statistical analysis
comparison['total_rentals'] = comparison['rentals_05_2005'] + comparison['rentals_06_2005']

print("Top 10 customers by total activity:")
top_customers = comparison.nlargest(10, 'total_rentals')[['customer_id', 'rentals_05_2005', 'rentals_06_2005', 'difference', 'total_rentals']]
display(top_customers)

Top 10 customers by total activity:

     customer_id  rentals_05_2005  rentals_06_2005  difference  total_rentals
195          197              8.0              8.0         0.0           16.0
175          176              5.0              8.0         3.0           13.0
369          371              6.0              7.0         1.0           13.0
108          109              7.0              5.0        -2.0           12.0
194          196              4.0              8.0         4.0           12.0
254          256              5.0              7.0         2.0           12.0
265          267              3.0              9.0         6.0           12.0
504          506              7.0              5.0        -2.0           12.0
524          526              3.0              9.0         6.0           12.0
30            31              0.0             11.0        11.0           11.0

In [36]:
# Customers with biggest increase from May to June
print("Top 10 customers with biggest increase from May to June:")
biggest_increase = comparison.nlargest(10, 'difference')[['customer_id', 'rentals_05_2005', 'rentals_06_2005', 'difference']]
display(biggest_increase)

Top 10 customers with biggest increase from May to June:

     customer_id  rentals_05_2005  rentals_06_2005  difference
30            31              0.0             11.0        11.0
327          329              0.0              9.0         9.0
452          454              1.0             10.0         9.0
177          178              0.0              8.0         8.0
211          213              1.0              9.0         8.0
266          268              0.0              8.0         8.0
293          295              1.0              9.0         8.0
334          336              0.0              8.0         8.0
338          340              0.0              8.0         8.0
455          457              1.0              9.0         8.0

In [37]:
# Customers with biggest decrease from May to June
print("Top 10 customers with biggest decrease from May to June:")
biggest_decrease = comparison.nsmallest(10, 'difference')[['customer_id', 'rentals_05_2005', 'rentals_06_2005', 'difference']]
display(biggest_decrease)

Top 10 customers with biggest decrease from May to June:

     customer_id  rentals_05_2005  rentals_06_2005  difference
205          207              6.0              1.0        -5.0
13            14              5.0              1.0        -4.0
160          161              6.0              2.0        -4.0
196          198              5.0              1.0        -4.0
248          250              5.0              1.0        -4.0
272          274              6.0              2.0        -4.0
594          596              6.0              2.0        -4.0
18            19              6.0              3.0        -3.0
123          124              4.0              1.0        -3.0
220          222              5.0              2.0        -3.0